#! /bin/bash

NAME="hyk"
DJK_DIR=/home/dev/workspaces/python-workspace/projects/hyk
VENV_DIR=/home/dev/workspaces/python-workspace/flask-env

echo "Starting $NAME"

cd $VENV_DIR
source bin/activate

cd $DJK_DIR

exec gunicorn app:application -c gunicorn_app_config.py

